[Build]
CacheDirectory=mkosi.cache

[Output]
Format=tar
Output=%d-%r_%v_%a
CompressOutput=xz
OutputDirectory=mkosi.output

[Content]
Packages=
        bash-completion
        dbus
        dnf
        iputils
        less
        ncurses
        passwd
        systemd
        util-linux
        vim-minimal

Autologin=yes
WithDocs=no

[Validation]
Checksum=yes
