[Build]
CacheDirectory=mkosi.cache

[Distribution]
Distribution=rhel-ubi
Release=10
Repositories=epel

[Output]
Format=tar
Output=%d-%r_%a
CompressOutput=xz
OutputDirectory=mkosi.output

[Content]
Packages=
        bash-completion
        dbus
        dnf
        glibc
        glibc-langpack-en
        iputils
        less
        ncurses
        passwd
        systemd
        util-linux
        vim-minimal

Autologin=yes
WithDocs=no

[Validation]
Checksum=yes
