name: Build and release

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/*
      - mkosi.**
  workflow_dispatch:
  schedule:
    - cron: 5 10 * * *

jobs:
  build-release:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    env:
      RELEASE_TAG: ${{ matrix.target.distro }}-${{ matrix.target.release }}_${{ matrix.arch }}
    strategy:
      matrix:
        target:
          - distro: centos
            release: 10
          - distro: fedora
            release: 44
          - distro: fedora
            release: rawhide
          - distro: rhel-ubi
            release: 10
        arch: [x86-64, arm64]
        include:
          - arch: x86-64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Install mkosi
        uses: systemd/mkosi@0e4d5546ac28500b1d41e8909cedf734b22cceab

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build image
        run: mkosi -d ${{ matrix.target.distro }} -r ${{ matrix.target.release }}

      - name: Delete symbolic links
        run: find mkosi.output -maxdepth 1 -type l -delete

      - name: Rename checksum file
        run: for f in *.SHA256SUMS; do mv $f SHA256SUMS; done
        working-directory: mkosi.output

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.RELEASE_TAG }}
          path: mkosi.output/*
          retention-days: 2

      - name: Release image
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete $RELEASE_TAG --cleanup-tag -y || true
          sleep 5
          gh release create $RELEASE_TAG mkosi.output/* -pt \
            "${{ matrix.target.distro }} ${{ matrix.target.release }} for ${{ matrix.arch }}"
