name: Build and release

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/*
      - mkosi.**
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * *

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        target:
          - distro: centos
            release: 10
          - distro: fedora
            release: 44
          - distro: fedora
            release: rawhide
          - distro: rhel-ubi
            release: 10
        arch: [x86-64, arm64]
        include:
          - arch: x86-64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Install mkosi
        uses: systemd/mkosi@d5ff0d0d9884cc4e06900057e2ad44adee29cb8e

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build image
        run: mkosi -d ${{ matrix.target.distro }} -r ${{ matrix.target.release }}

      - name: Generate checksum file
        run: for f in *; do sha256sum $f > $f.sha256; done
        working-directory: mkosi.output

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target.distro }}-${{ matrix.target.release }}_${{ matrix.arch }}
          path: mkosi.output/*
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag -y || true
          sleep 5
          gh release create latest artifacts/* -t $(date -u +%F)
